// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface CancelMeetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.CancelMeetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string cancel_meeting_id = 1;</code>
   */
  java.lang.String getCancelMeetingId();
  /**
   * <code>string cancel_meeting_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCancelMeetingIdBytes();
}
