// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface CancelMeetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.CancelMeetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string successCancel = 1;</code>
   */
  java.lang.String getSuccessCancel();
  /**
   * <code>string successCancel = 1;</code>
   */
  com.google.protobuf.ByteString
      getSuccessCancelBytes();

  /**
   * <code>string error_message = 2;</code>
   */
  java.lang.String getErrorMessage();
  /**
   * <code>string error_message = 2;</code>
   */
  com.google.protobuf.ByteString
      getErrorMessageBytes();
}
