// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface CreateMeetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.CreateMeetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string organizer_id = 1;</code>
   */
  java.lang.String getOrganizerId();
  /**
   * <code>string organizer_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getOrganizerIdBytes();

  /**
   * <code>string title = 2;</code>
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>int64 start_time = 3;</code>
   */
  long getStartTime();
}
