// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface CreateMeetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.CreateMeetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string meeting_id = 1;</code>
   */
  java.lang.String getMeetingId();
  /**
   * <code>string meeting_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getMeetingIdBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
