// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface ModifyMeetingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.ModifyMeetingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string modi_meeting_id = 1;</code>
   */
  java.lang.String getModiMeetingId();
  /**
   * <code>string modi_meeting_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getModiMeetingIdBytes();

  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  boolean hasUpdates();
  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  meeting.service1.UpdateMessage getUpdates();
  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  meeting.service1.UpdateMessageOrBuilder getUpdatesOrBuilder();
}
