// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface ModifyMeetingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.ModifyMeetingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool successModify = 1;</code>
   */
  boolean getSuccessModify();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
