// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

/**
 * Protobuf type {@code Smart.HR_Office.ModifyMeetingRequest}
 */
public  final class ModifyMeetingRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Smart.HR_Office.ModifyMeetingRequest)
    ModifyMeetingRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ModifyMeetingRequest.newBuilder() to construct.
  private ModifyMeetingRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ModifyMeetingRequest() {
    modiMeetingId_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ModifyMeetingRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            modiMeetingId_ = s;
            break;
          }
          case 18: {
            meeting.service1.UpdateMessage.Builder subBuilder = null;
            if (updates_ != null) {
              subBuilder = updates_.toBuilder();
            }
            updates_ = input.readMessage(meeting.service1.UpdateMessage.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(updates_);
              updates_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return meeting.service1.Service1_Impl.internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return meeting.service1.Service1_Impl.internal_static_Smart_HR_Office_ModifyMeetingRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            meeting.service1.ModifyMeetingRequest.class, meeting.service1.ModifyMeetingRequest.Builder.class);
  }

  public static final int MODI_MEETING_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object modiMeetingId_;
  /**
   * <code>string modi_meeting_id = 1;</code>
   */
  public java.lang.String getModiMeetingId() {
    java.lang.Object ref = modiMeetingId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      modiMeetingId_ = s;
      return s;
    }
  }
  /**
   * <code>string modi_meeting_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getModiMeetingIdBytes() {
    java.lang.Object ref = modiMeetingId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      modiMeetingId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int UPDATES_FIELD_NUMBER = 2;
  private meeting.service1.UpdateMessage updates_;
  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  public boolean hasUpdates() {
    return updates_ != null;
  }
  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  public meeting.service1.UpdateMessage getUpdates() {
    return updates_ == null ? meeting.service1.UpdateMessage.getDefaultInstance() : updates_;
  }
  /**
   * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
   */
  public meeting.service1.UpdateMessageOrBuilder getUpdatesOrBuilder() {
    return getUpdates();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getModiMeetingIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, modiMeetingId_);
    }
    if (updates_ != null) {
      output.writeMessage(2, getUpdates());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getModiMeetingIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, modiMeetingId_);
    }
    if (updates_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getUpdates());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof meeting.service1.ModifyMeetingRequest)) {
      return super.equals(obj);
    }
    meeting.service1.ModifyMeetingRequest other = (meeting.service1.ModifyMeetingRequest) obj;

    boolean result = true;
    result = result && getModiMeetingId()
        .equals(other.getModiMeetingId());
    result = result && (hasUpdates() == other.hasUpdates());
    if (hasUpdates()) {
      result = result && getUpdates()
          .equals(other.getUpdates());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MODI_MEETING_ID_FIELD_NUMBER;
    hash = (53 * hash) + getModiMeetingId().hashCode();
    if (hasUpdates()) {
      hash = (37 * hash) + UPDATES_FIELD_NUMBER;
      hash = (53 * hash) + getUpdates().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static meeting.service1.ModifyMeetingRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static meeting.service1.ModifyMeetingRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static meeting.service1.ModifyMeetingRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static meeting.service1.ModifyMeetingRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(meeting.service1.ModifyMeetingRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Smart.HR_Office.ModifyMeetingRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Smart.HR_Office.ModifyMeetingRequest)
      meeting.service1.ModifyMeetingRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return meeting.service1.Service1_Impl.internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return meeting.service1.Service1_Impl.internal_static_Smart_HR_Office_ModifyMeetingRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              meeting.service1.ModifyMeetingRequest.class, meeting.service1.ModifyMeetingRequest.Builder.class);
    }

    // Construct using meeting.service1.ModifyMeetingRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      modiMeetingId_ = "";

      if (updatesBuilder_ == null) {
        updates_ = null;
      } else {
        updates_ = null;
        updatesBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return meeting.service1.Service1_Impl.internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor;
    }

    @java.lang.Override
    public meeting.service1.ModifyMeetingRequest getDefaultInstanceForType() {
      return meeting.service1.ModifyMeetingRequest.getDefaultInstance();
    }

    @java.lang.Override
    public meeting.service1.ModifyMeetingRequest build() {
      meeting.service1.ModifyMeetingRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public meeting.service1.ModifyMeetingRequest buildPartial() {
      meeting.service1.ModifyMeetingRequest result = new meeting.service1.ModifyMeetingRequest(this);
      result.modiMeetingId_ = modiMeetingId_;
      if (updatesBuilder_ == null) {
        result.updates_ = updates_;
      } else {
        result.updates_ = updatesBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof meeting.service1.ModifyMeetingRequest) {
        return mergeFrom((meeting.service1.ModifyMeetingRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(meeting.service1.ModifyMeetingRequest other) {
      if (other == meeting.service1.ModifyMeetingRequest.getDefaultInstance()) return this;
      if (!other.getModiMeetingId().isEmpty()) {
        modiMeetingId_ = other.modiMeetingId_;
        onChanged();
      }
      if (other.hasUpdates()) {
        mergeUpdates(other.getUpdates());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      meeting.service1.ModifyMeetingRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (meeting.service1.ModifyMeetingRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object modiMeetingId_ = "";
    /**
     * <code>string modi_meeting_id = 1;</code>
     */
    public java.lang.String getModiMeetingId() {
      java.lang.Object ref = modiMeetingId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modiMeetingId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string modi_meeting_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModiMeetingIdBytes() {
      java.lang.Object ref = modiMeetingId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modiMeetingId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string modi_meeting_id = 1;</code>
     */
    public Builder setModiMeetingId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      modiMeetingId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string modi_meeting_id = 1;</code>
     */
    public Builder clearModiMeetingId() {
      
      modiMeetingId_ = getDefaultInstance().getModiMeetingId();
      onChanged();
      return this;
    }
    /**
     * <code>string modi_meeting_id = 1;</code>
     */
    public Builder setModiMeetingIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      modiMeetingId_ = value;
      onChanged();
      return this;
    }

    private meeting.service1.UpdateMessage updates_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        meeting.service1.UpdateMessage, meeting.service1.UpdateMessage.Builder, meeting.service1.UpdateMessageOrBuilder> updatesBuilder_;
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public boolean hasUpdates() {
      return updatesBuilder_ != null || updates_ != null;
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public meeting.service1.UpdateMessage getUpdates() {
      if (updatesBuilder_ == null) {
        return updates_ == null ? meeting.service1.UpdateMessage.getDefaultInstance() : updates_;
      } else {
        return updatesBuilder_.getMessage();
      }
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public Builder setUpdates(meeting.service1.UpdateMessage value) {
      if (updatesBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        updates_ = value;
        onChanged();
      } else {
        updatesBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public Builder setUpdates(
        meeting.service1.UpdateMessage.Builder builderForValue) {
      if (updatesBuilder_ == null) {
        updates_ = builderForValue.build();
        onChanged();
      } else {
        updatesBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public Builder mergeUpdates(meeting.service1.UpdateMessage value) {
      if (updatesBuilder_ == null) {
        if (updates_ != null) {
          updates_ =
            meeting.service1.UpdateMessage.newBuilder(updates_).mergeFrom(value).buildPartial();
        } else {
          updates_ = value;
        }
        onChanged();
      } else {
        updatesBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public Builder clearUpdates() {
      if (updatesBuilder_ == null) {
        updates_ = null;
        onChanged();
      } else {
        updates_ = null;
        updatesBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public meeting.service1.UpdateMessage.Builder getUpdatesBuilder() {
      
      onChanged();
      return getUpdatesFieldBuilder().getBuilder();
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    public meeting.service1.UpdateMessageOrBuilder getUpdatesOrBuilder() {
      if (updatesBuilder_ != null) {
        return updatesBuilder_.getMessageOrBuilder();
      } else {
        return updates_ == null ?
            meeting.service1.UpdateMessage.getDefaultInstance() : updates_;
      }
    }
    /**
     * <code>.Smart.HR_Office.UpdateMessage updates = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        meeting.service1.UpdateMessage, meeting.service1.UpdateMessage.Builder, meeting.service1.UpdateMessageOrBuilder> 
        getUpdatesFieldBuilder() {
      if (updatesBuilder_ == null) {
        updatesBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            meeting.service1.UpdateMessage, meeting.service1.UpdateMessage.Builder, meeting.service1.UpdateMessageOrBuilder>(
                getUpdates(),
                getParentForChildren(),
                isClean());
        updates_ = null;
      }
      return updatesBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Smart.HR_Office.ModifyMeetingRequest)
  }

  // @@protoc_insertion_point(class_scope:Smart.HR_Office.ModifyMeetingRequest)
  private static final meeting.service1.ModifyMeetingRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new meeting.service1.ModifyMeetingRequest();
  }

  public static meeting.service1.ModifyMeetingRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ModifyMeetingRequest>
      PARSER = new com.google.protobuf.AbstractParser<ModifyMeetingRequest>() {
    @java.lang.Override
    public ModifyMeetingRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ModifyMeetingRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ModifyMeetingRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ModifyMeetingRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public meeting.service1.ModifyMeetingRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

