// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public final class Service1_Impl {
  private Service1_Impl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_CreateMeetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_CreateMeetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_CreateMeetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_CreateMeetingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_UpdateMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_UpdateMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_ModifyMeetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_ModifyMeetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_ModifyMeetingResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_CancelMeetingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_CancelMeetingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Smart_HR_Office_CancelMeetingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Smart_HR_Office_CancelMeetingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035smart_Schedule_meeting1.proto\022\017Smart.H" +
      "R_Office\"O\n\024CreateMeetingRequest\022\024\n\014orga" +
      "nizer_id\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\022\n\nstart_t" +
      "ime\030\003 \001(\003\"<\n\025CreateMeetingResponse\022\022\n\nme" +
      "eting_id\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\"4\n\rUpdat" +
      "eMessage\022\022\n\nsession_id\030\001 \001(\t\022\017\n\007updates\030" +
      "\002 \003(\t\"`\n\024ModifyMeetingRequest\022\027\n\017modi_me" +
      "eting_id\030\001 \001(\t\022/\n\007updates\030\002 \001(\0132\036.Smart." +
      "HR_Office.UpdateMessage\"?\n\025ModifyMeeting" +
      "Response\022\025\n\rsuccessModify\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t\"1\n\024CancelMeetingRequest\022\031\n\021canc" +
      "el_meeting_id\030\001 \001(\t\"E\n\025CancelMeetingResp" +
      "onse\022\025\n\rsuccessCancel\030\001 \001(\t\022\025\n\rerror_mes" +
      "sage\030\002 \001(\t2\300\002\n\020Schedule_Meeting\022b\n\rCreat" +
      "eMeeting\022%.Smart.HR_Office.CreateMeeting" +
      "Request\032&.Smart.HR_Office.CreateMeetingR" +
      "esponse\"\000(\001\022d\n\rModifyMeeting\022%.Smart.HR_" +
      "Office.ModifyMeetingRequest\032&.Smart.HR_O" +
      "ffice.ModifyMeetingResponse\"\000(\0010\001\022b\n\rCan" +
      "celMeeting\022%.Smart.HR_Office.CancelMeeti" +
      "ngRequest\032&.Smart.HR_Office.CancelMeetin" +
      "gResponse\"\0000\001B#\n\020meeting.service1B\rServi" +
      "ce1_ImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Smart_HR_Office_CreateMeetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Smart_HR_Office_CreateMeetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_CreateMeetingRequest_descriptor,
        new java.lang.String[] { "OrganizerId", "Title", "StartTime", });
    internal_static_Smart_HR_Office_CreateMeetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Smart_HR_Office_CreateMeetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_CreateMeetingResponse_descriptor,
        new java.lang.String[] { "MeetingId", "Message", });
    internal_static_Smart_HR_Office_UpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Smart_HR_Office_UpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_UpdateMessage_descriptor,
        new java.lang.String[] { "SessionId", "Updates", });
    internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Smart_HR_Office_ModifyMeetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_ModifyMeetingRequest_descriptor,
        new java.lang.String[] { "ModiMeetingId", "Updates", });
    internal_static_Smart_HR_Office_ModifyMeetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_Smart_HR_Office_ModifyMeetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_ModifyMeetingResponse_descriptor,
        new java.lang.String[] { "SuccessModify", "Message", });
    internal_static_Smart_HR_Office_CancelMeetingRequest_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_Smart_HR_Office_CancelMeetingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_CancelMeetingRequest_descriptor,
        new java.lang.String[] { "CancelMeetingId", });
    internal_static_Smart_HR_Office_CancelMeetingResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_Smart_HR_Office_CancelMeetingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Smart_HR_Office_CancelMeetingResponse_descriptor,
        new java.lang.String[] { "SuccessCancel", "ErrorMessage", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
