// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Schedule_meeting1.proto

package meeting.service1;

public interface UpdateMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.UpdateMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_id = 1;</code>
   */
  java.lang.String getSessionId();
  /**
   * <code>string session_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionIdBytes();

  /**
   * <pre>
   * kind of array
   * </pre>
   *
   * <code>repeated string updates = 2;</code>
   */
  java.util.List<java.lang.String>
      getUpdatesList();
  /**
   * <pre>
   * kind of array
   * </pre>
   *
   * <code>repeated string updates = 2;</code>
   */
  int getUpdatesCount();
  /**
   * <pre>
   * kind of array
   * </pre>
   *
   * <code>repeated string updates = 2;</code>
   */
  java.lang.String getUpdates(int index);
  /**
   * <pre>
   * kind of array
   * </pre>
   *
   * <code>repeated string updates = 2;</code>
   */
  com.google.protobuf.ByteString
      getUpdatesBytes(int index);
}
