// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Onboarding3.proto

package onboarding.service3;

public interface EmployeeStatusRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.EmployeeStatusRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employee_id = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employee_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();
}
