// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Onboarding3.proto

package onboarding.service3;

public interface EmployeeStatusResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.EmployeeStatusResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string employee_id = 1;</code>
   */
  java.lang.String getEmployeeId();
  /**
   * <code>string employee_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getEmployeeIdBytes();

  /**
   * <code>bool is_employee_active = 2;</code>
   */
  boolean getIsEmployeeActive();
}
