// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Onboarding3.proto

package onboarding.service3;

public interface OnboardingRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.OnboardingRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Smart.HR_Office.Employee employee = 1;</code>
   */
  boolean hasEmployee();
  /**
   * <code>.Smart.HR_Office.Employee employee = 1;</code>
   */
  onboarding.service3.Employee getEmployee();
  /**
   * <code>.Smart.HR_Office.Employee employee = 1;</code>
   */
  onboarding.service3.EmployeeOrBuilder getEmployeeOrBuilder();
}
