// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Onboarding3.proto

package onboarding.service3;

public interface OnboardingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.OnboardingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool is_onboarded = 1;</code>
   */
  boolean getIsOnboarded();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
