// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

/**
 * Protobuf type {@code Smart.HR_Office.AdjustRoomTemperatureRequest}
 */
public  final class AdjustRoomTemperatureRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:Smart.HR_Office.AdjustRoomTemperatureRequest)
    AdjustRoomTemperatureRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use AdjustRoomTemperatureRequest.newBuilder() to construct.
  private AdjustRoomTemperatureRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private AdjustRoomTemperatureRequest() {
    adjRoomNumber_ = 0;
    temperatureAdjustment_ = 0D;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private AdjustRoomTemperatureRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            adjRoomNumber_ = input.readInt32();
            break;
          }
          case 17: {

            temperatureAdjustment_ = input.readDouble();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return temperature.service2.Service2_Impl.internal_static_Smart_HR_Office_AdjustRoomTemperatureRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return temperature.service2.Service2_Impl.internal_static_Smart_HR_Office_AdjustRoomTemperatureRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            temperature.service2.AdjustRoomTemperatureRequest.class, temperature.service2.AdjustRoomTemperatureRequest.Builder.class);
  }

  public static final int ADJ_ROOM_NUMBER_FIELD_NUMBER = 1;
  private int adjRoomNumber_;
  /**
   * <code>int32 adj_room_number = 1;</code>
   */
  public int getAdjRoomNumber() {
    return adjRoomNumber_;
  }

  public static final int TEMPERATURE_ADJUSTMENT_FIELD_NUMBER = 2;
  private double temperatureAdjustment_;
  /**
   * <code>double temperature_adjustment = 2;</code>
   */
  public double getTemperatureAdjustment() {
    return temperatureAdjustment_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (adjRoomNumber_ != 0) {
      output.writeInt32(1, adjRoomNumber_);
    }
    if (temperatureAdjustment_ != 0D) {
      output.writeDouble(2, temperatureAdjustment_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (adjRoomNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, adjRoomNumber_);
    }
    if (temperatureAdjustment_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(2, temperatureAdjustment_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof temperature.service2.AdjustRoomTemperatureRequest)) {
      return super.equals(obj);
    }
    temperature.service2.AdjustRoomTemperatureRequest other = (temperature.service2.AdjustRoomTemperatureRequest) obj;

    boolean result = true;
    result = result && (getAdjRoomNumber()
        == other.getAdjRoomNumber());
    result = result && (
        java.lang.Double.doubleToLongBits(getTemperatureAdjustment())
        == java.lang.Double.doubleToLongBits(
            other.getTemperatureAdjustment()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ADJ_ROOM_NUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getAdjRoomNumber();
    hash = (37 * hash) + TEMPERATURE_ADJUSTMENT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTemperatureAdjustment()));
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static temperature.service2.AdjustRoomTemperatureRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(temperature.service2.AdjustRoomTemperatureRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code Smart.HR_Office.AdjustRoomTemperatureRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:Smart.HR_Office.AdjustRoomTemperatureRequest)
      temperature.service2.AdjustRoomTemperatureRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return temperature.service2.Service2_Impl.internal_static_Smart_HR_Office_AdjustRoomTemperatureRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return temperature.service2.Service2_Impl.internal_static_Smart_HR_Office_AdjustRoomTemperatureRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              temperature.service2.AdjustRoomTemperatureRequest.class, temperature.service2.AdjustRoomTemperatureRequest.Builder.class);
    }

    // Construct using temperature.service2.AdjustRoomTemperatureRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      adjRoomNumber_ = 0;

      temperatureAdjustment_ = 0D;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return temperature.service2.Service2_Impl.internal_static_Smart_HR_Office_AdjustRoomTemperatureRequest_descriptor;
    }

    @java.lang.Override
    public temperature.service2.AdjustRoomTemperatureRequest getDefaultInstanceForType() {
      return temperature.service2.AdjustRoomTemperatureRequest.getDefaultInstance();
    }

    @java.lang.Override
    public temperature.service2.AdjustRoomTemperatureRequest build() {
      temperature.service2.AdjustRoomTemperatureRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public temperature.service2.AdjustRoomTemperatureRequest buildPartial() {
      temperature.service2.AdjustRoomTemperatureRequest result = new temperature.service2.AdjustRoomTemperatureRequest(this);
      result.adjRoomNumber_ = adjRoomNumber_;
      result.temperatureAdjustment_ = temperatureAdjustment_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof temperature.service2.AdjustRoomTemperatureRequest) {
        return mergeFrom((temperature.service2.AdjustRoomTemperatureRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(temperature.service2.AdjustRoomTemperatureRequest other) {
      if (other == temperature.service2.AdjustRoomTemperatureRequest.getDefaultInstance()) return this;
      if (other.getAdjRoomNumber() != 0) {
        setAdjRoomNumber(other.getAdjRoomNumber());
      }
      if (other.getTemperatureAdjustment() != 0D) {
        setTemperatureAdjustment(other.getTemperatureAdjustment());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      temperature.service2.AdjustRoomTemperatureRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (temperature.service2.AdjustRoomTemperatureRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int adjRoomNumber_ ;
    /**
     * <code>int32 adj_room_number = 1;</code>
     */
    public int getAdjRoomNumber() {
      return adjRoomNumber_;
    }
    /**
     * <code>int32 adj_room_number = 1;</code>
     */
    public Builder setAdjRoomNumber(int value) {
      
      adjRoomNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 adj_room_number = 1;</code>
     */
    public Builder clearAdjRoomNumber() {
      
      adjRoomNumber_ = 0;
      onChanged();
      return this;
    }

    private double temperatureAdjustment_ ;
    /**
     * <code>double temperature_adjustment = 2;</code>
     */
    public double getTemperatureAdjustment() {
      return temperatureAdjustment_;
    }
    /**
     * <code>double temperature_adjustment = 2;</code>
     */
    public Builder setTemperatureAdjustment(double value) {
      
      temperatureAdjustment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double temperature_adjustment = 2;</code>
     */
    public Builder clearTemperatureAdjustment() {
      
      temperatureAdjustment_ = 0D;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:Smart.HR_Office.AdjustRoomTemperatureRequest)
  }

  // @@protoc_insertion_point(class_scope:Smart.HR_Office.AdjustRoomTemperatureRequest)
  private static final temperature.service2.AdjustRoomTemperatureRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new temperature.service2.AdjustRoomTemperatureRequest();
  }

  public static temperature.service2.AdjustRoomTemperatureRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<AdjustRoomTemperatureRequest>
      PARSER = new com.google.protobuf.AbstractParser<AdjustRoomTemperatureRequest>() {
    @java.lang.Override
    public AdjustRoomTemperatureRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new AdjustRoomTemperatureRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<AdjustRoomTemperatureRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<AdjustRoomTemperatureRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public temperature.service2.AdjustRoomTemperatureRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

