// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

public interface AdjustRoomTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.AdjustRoomTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 adj_room_number = 1;</code>
   */
  int getAdjRoomNumber();

  /**
   * <code>double temperature_adjustment = 2;</code>
   */
  double getTemperatureAdjustment();
}
