// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

public interface AdjustRoomTemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.AdjustRoomTemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 new_adj_temperature = 1;</code>
   */
  int getNewAdjTemperature();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
