// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

public interface RoomTemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.RoomTemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 room_number = 1;</code>
   */
  int getRoomNumber();
}
