// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

public interface TemperatureResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.TemperatureResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double current_temperature = 1;</code>
   */
  double getCurrentTemperature();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
