// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smart_Room_Temperature2.proto

package temperature.service2;

public interface TemperatureRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Smart.HR_Office.TemperatureRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 set_room_number = 1;</code>
   */
  int getSetRoomNumber();

  /**
   * <code>double set_temperature = 2;</code>
   */
  double getSetTemperature();
}
